const path = 'assets/icons/';
const extension = '.svg';

export const Icons = {
  ADD_CIRCLE: { name: 'add_circle', path: path + 'ic_add_circle' + extension },
  MENU: { name: 'menu', path: path + 'ic_menu' + extension },
  SEND: { name: 'send', path: path + 'ic_send' + extension },
  BELL: { name: 'bell', path: path + 'ic_bell' + extension },
  HOME: { name: 'home', path: path + 'ic_home' + extension },
  HISTORY: { name: 'history', path: path + 'ic_history' + extension },
  SETTINGS: { name: 'settings', path: path + 'ic_settings' + extension },
  TIME: { name: 'time', path: path + 'ic_time' + extension },
  CHEVRON_LEFT: { name: 'chevron_left', path: path + 'ic_chevron_left' + extension },
  EXPAND_LESS: { name: 'expand_less', path: path + 'ic_expand_less' + extension },
  EXPAND_MORE: { name: 'expand_more', path: path + 'ic_expand_more' + extension },
  EXPAND: { name: 'expand_solid', path: path + 'ic_expand_solid' + extension },
  COG_WHEEL: { name: 'cog_wheel', path: path + 'ic_cog_wheel' + extension },
  THUMBS_UP: { name: 'thumbs_up', path: path + 'ic_thumbs_up' + extension },
  MORE_DETAILS: { name: 'more_details', path: path + 'ic_more_details' + extension },
  CROSS: { name: 'cross', path: path + 'ic_cross' + extension },
  LOCK: { name: 'lock', path: path + 'ic_lock' + extension },
  EMAIL: { name: 'email', path: path + 'ic_email' + extension },
  EYE: { name: 'eye', path: path + 'ic_eye' + extension },
  SOURCETREE_BRANDS: { name: 'sourcetree_brands', path: path + 'ic_sourcetree_brands' + extension },
  DIRECTIONS_SOLID: { name: 'directions_solid', path: path + 'ic_directions_solid' + extension },
  EYE_SLASH: { name: 'eye_slash', path: path + 'ic_eye_slash' + extension },
  WARNING: { name: 'warning', path: path + 'ic_warning' + extension },
  INFORMATION: { name: 'information', path: path + 'ic_information' + extension },
  ERROR: { name: 'error', path: path + 'ic_error' + extension },
  CHECK: { name: 'check', path: path + 'ic_check' + extension },
  INFORMATION_OUTLINED: { name: 'information_outlined', path: path + 'ic_information_outlined' + extension },
  FAVICON: { name: 'favicon', path: 'assets/favicons/favicon.ico' },
  FAVICON_NOTIFICATION: { name: 'favicon_notification', path: 'assets/favicons/favicon_notifications.ico' },
  MET: { name: 'met', path: path + 'ic_met' + extension },
  QUESTION: { name: 'question', path: path + 'ic_question' + extension },
  BLOCK: { name: 'block', path: path + 'ic_block' + extension },
  MINUS: { name: 'minus', path: path + 'ic_minus' + extension },
  PLUS: { name: 'plus', path: path + 'ic_plus' + extension },
  SEARCH: { name: 'search', path: path + 'ic_search' + extension },
  GROUP: { name: 'group', path: path + 'ic_group' + extension },
  TRASH: { name: 'trash', path: path + 'ic_trash' + extension },
  USER: { name: 'user', path: path + 'ic_user' + extension },
  RESPONSABLE: { name: 'responsable', path: path + 'ic_responsable' + extension },
  ARROW_UP: { name: 'arrow_up', path: path + 'ic_arrow_up' + extension },
  ARROW_DOWN: { name: 'arrow_down', path: path + 'ic_arrow_down' + extension }
};
